# PyTorch basic commands and functions

In [1]:
from __future__ import print_function
import numpy as np
import torch

Create empty 5x3 uninitialized matrix

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[-3.0471e-12,  4.5808e-41, -3.0471e-12],
        [ 4.5808e-41,  1.4602e-19,  1.8617e+25],
        [ 1.1835e+22,  4.3066e+21,  6.3828e+28],
        [ 1.4603e-19,  1.1578e+27,  1.1362e+30],
        [ 7.1547e+22,  4.5828e+30,  1.2121e+04]])


Create 5x3 zeros matrix of data type long.

In [3]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Create a tensor filled with own data.

In [4]:
x = torch.tensor([[5, 3],[4,5]])
y = torch.tensor([5,3])
print("x tensor")
print(x)
print("y tensor")
print(y)

x tensor
tensor([[5, 3],
        [4, 5]])
y tensor
tensor([5, 3])


Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.

In [5]:
x = x.new_ones(5,3, dtype=torch.double) # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
x = torch.randn_like(x, dtype=torch.float) #override dtype
print(x)
print(x.size())

tensor([[-0.2881,  0.5879,  2.0881],
        [-0.7459, -0.6295, -0.5308],
        [ 1.8846, -0.8471, -0.9990],
        [-0.7039,  0.1646, -0.0567],
        [ 0.7604,  0.3752,  1.1446]])
torch.Size([5, 3])


### Operations
There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation. <br>
Syntax 1:

In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3227,  0.7441,  2.1332],
        [-0.2204, -0.5258, -0.5190],
        [ 2.5684, -0.4185, -0.8491],
        [-0.0725,  0.8600,  0.2487],
        [ 1.4284,  1.3115,  2.1155]])


Syntax 2:

In [8]:
print(torch.add(x, y))

tensor([[ 0.3227,  0.7441,  2.1332],
        [-0.2204, -0.5258, -0.5190],
        [ 2.5684, -0.4185, -0.8491],
        [-0.0725,  0.8600,  0.2487],
        [ 1.4284,  1.3115,  2.1155]])


Syntax 3:

In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result) #provide output tensor as argument
print(result)

tensor([[ 0.3227,  0.7441,  2.1332],
        [-0.2204, -0.5258, -0.5190],
        [ 2.5684, -0.4185, -0.8491],
        [-0.0725,  0.8600,  0.2487],
        [ 1.4284,  1.3115,  2.1155]])


Syntax 4: in-place addition

In [10]:
y.add_(x)
print(y)

tensor([[ 0.3227,  0.7441,  2.1332],
        [-0.2204, -0.5258, -0.5190],
        [ 2.5684, -0.4185, -0.8491],
        [-0.0725,  0.8600,  0.2487],
        [ 1.4284,  1.3115,  2.1155]])


Any operation that mutates a tensor in-place is post-fixed with an `_`

Resizing: If we want to resize/reshape tensor, we can use `torch.view'

In [11]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## Converting a Torch Tensor to a NumPy Array

In [12]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


We can convert Tensor Torch to a Numpy array as shown below using `.numpy` function.

In [13]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other. Basically `b` acts as a pointer to `a`. So changing the value of `a` will also change the value of `b`

In [14]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting a NumPy Array to a Torch Tensor
NumPy array can be converted to a Torch Tensor using `torch.from_numpy()` function.

In [15]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a, 1, out=a)
print("after addition")
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
after addition
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
Tensors can be moved onto any device using the `.to` method

In [16]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", dtype=torch.double))

tensor([[1.1205, 1.1503, 1.8551, 1.7115],
        [1.5826, 1.3644, 1.1344, 1.8511],
        [1.7183, 1.0083, 1.5709, 1.4749],
        [1.8847, 1.8259, 1.8725, 1.2254]], device='cuda:0')
tensor([[1.1205, 1.1503, 1.8551, 1.7115],
        [1.5826, 1.3644, 1.1344, 1.8511],
        [1.7183, 1.0083, 1.5709, 1.4749],
        [1.8847, 1.8259, 1.8725, 1.2254]], dtype=torch.float64)


# Autograd


Create a tensor and set `requires_grad=True` to track computation with it

In [17]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation and store it in y. y is created as a result of an operation, so it has `grad_fn` associated with it.

In [18]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [19]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


`.requires_grad_( ... )` changes an existing Tensor’s `requires_grad` flag in-place. The input flag defaults to `False` if not given

In [20]:
a = torch.randn(2,2)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b)

False
True
tensor(5.7331, grad_fn=<SumBackward0>)


Do backpropogation and Print gradients d(out)/dx

In [21]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
